kffz/comment/urls.py
from django.urls import path,re_path
from . import views

app_name = 'comment'
urlpatterns = [
    re_path(r'^comment/article-list/(?P<blog_pk>[0-9]+)',views.blog_comment,name='blog_comment')
]

kffz/homepage/urls.py
#coding=UTF-8
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views
import re

app_name = 'homepage'
urlpatterns = [
    path('', views.IndexView.as_view(), name="home"),
    re_path(r'index.html',views.IndexView.as_view()),
    path('signup/', views.signup),
    path('articles-list/', views.Article_list.as_view()),
    path('faq/',views.Faq_list.as_view()),
    path('contact/',views.Contact_list.as_view()),
    re_path(r'more[0-9]+/',views.more.as_view()),
    re_path(r'child[0-9]+/',views.child.as_view()),
    re_path(r'articles-list.html',views.Article_list.as_view()),
    path('logout/', views.logout_view),
    re_path(r'^articles-list/(?P<pk>[0-9]+)/', views.BlogDetailView.as_view(), name='detail'),
]

kffz/kffz/urls.py
#coding=UTF-8
"""kffz URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include,path,re_path
from homepage.feeds import AllBlogsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls'),name = "home"),
    re_path(r'index.html',include('homepage.urls')),
    re_path(r'articles-list.html',include('homepage.urls')),
    path('faq/',include('homepage.urls')),
    path('contact/',include('homepage.urls')),
    path('diy/',include('diy.urls')),
    path('signup/',include('homepage.urls')),
    path('articles-list.html',include('homepage.urls')),
    path('logout/',include('homepage.urls')),
    re_path(r'child[0-9]+/',include('homepage.urls')),
    re_path(r'more[0-9]+/',include('homepage.urls')),
    re_path(r'^articles-list/(?P<pk>[0-9]+)/',include('homepage.urls'),name = 'detail'),
    re_path(r'',include('comment.urls')),
    path('all/rss/',AllBlogsRssFeed(),name = 'rss'),
    re_path(r'cpu_finder',include('diy.urls')),
    re_path(r'search/',include('haystack.urls'),name = 'search'),
]

kffz/comment/models.py
from django.db import models
from homepage import models as homemodel
# Create your models here.
class Comment(models.Model):
    n_comment = models.IntegerField(default=0)
    blog = models.ForeignKey(homemodel.Blog,on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.content[:10]

kffz/homepage/models.py
#coding=UTF-8
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.html import strip_tags
import markdown
# Create your models here.

class Myuser(AbstractUser):
    jifen = models.IntegerField('积分',default=0)
    class Meta:
        db_table = 'Myuser'
    def __str__(self):
        return self.username

class BlogCategory(models.Model):
    techology = '科技&DIY'
    finance = '财经'
    coding = '技术'
    reading = '阅读'
    enjoy = '娱乐'
    zero = 0
    CATEGORY_CHOICES = (
        (techology, '科技&DIY'),
        (finance,'财经'),
        (coding,'技术'),
        (reading,'阅读'),
        (enjoy,'娱乐')
    )
    catogory = models.CharField(max_length=10,choices=CATEGORY_CHOICES,default=coding)
    name = models.CharField(max_length=10,default='技术')

class Blog(models.Model):
    title = models.CharField(max_length=50)
    tagline = models.TextField()
    detail = models.TextField()
    pub_date = models.DateField(auto_now_add=True)
    mod_date = models.DateField(auto_now=True)
    authors = models.ForeignKey(Myuser,on_delete=models.CASCADE)
    n_comment = models.IntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    category = models.CharField(max_length=10,choices=BlogCategory.CATEGORY_CHOICES,null=True)
    excerpt = models.CharField(max_length=200,blank=True)
    class Meta:
        ordering = ['-pub_date','views']
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('homepage:detail',kwargs={'pk':self.pk})
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.detail))[:54]

        super(Blog, self).save(*args, **kwargs)

kffz/homepage/forms.py
#coding=UTF-8
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate

import re

class SignupForm(forms.ModelForm):
    username = forms.CharField(label='用户名',required=True,error_messages={'required':'Please enter your username','max_length':'over 16','min_length':'less than 4'},\
                               max_length=16,min_length=4,widget=forms.TextInput(attrs={'placeholder':'4~16'}));
    email = forms.EmailField(label='email',error_messages={'required':'Please enter your email','invalid':'Please enter the correct email'});
    password = forms.CharField(label='密码',required=True,error_messages={'required':'Please enter your password','max_length':'over 20',\
                                                             'min_length':'less than 6'},max_length=20,min_length=6,widget=forms.PasswordInput(attrs={'placeholder':'6-20'}));
    confirm_password = forms.CharField(error_messages={'required':'Please enter your password','max_length':'over 20','min_length':'less than 6'}, \
                                       label='确认密码', max_length=20, min_length=6, widget=forms.PasswordInput(attrs={'placeholder': '6-20'}))
    class Meta:
        model = get_user_model()
        fields = ('username','email','password')


    def cleaned_email(self):
        UserModel = get_user_model()
        email  = self.cleaned_data['email']
        try:
            UserModel._default_manager.get(email=email)
        except:
            return email
        raise forms.ValidationError('该邮箱地址已被注册')

    def clean_confirm_password(self):
         password = self.cleaned_data['password']
         confirm_password = self.cleaned_data['confirm_password']
         if not(password == confirm_password):
              raise forms.ValidationError('确认密码和密码不一致')
         return confirm_password

    def clean_username(self):
        UserModel = get_user_model()
        username = self.cleaned_data['username']
        n=re.sub('[^\u4e00-\u9fa5a-zA-Z]','',username)
        mgc = ['admin','qaq','kffz','KFFZ']
        if n in mgc:
            raise forms.ValidationError('Please change an username')
        try:
            UserModel._default_manager.get(username=username)
        except:
            return username
        raise forms.ValidationError('有人已经注册了该名称')

#class ArticleForm(forms.ModelForm):
    #title = forms.CharField(label="标题",required=True,error_messages={'required':'请输入您文章标题','max_length':'标题长度不超过30个字','min_length':'标题长度不小于5个字'},\
    #                        max_length=30,min_length=5,widget=forms.TextInput(attrs={'placeholder':'请输入您文章标题，5到30字之间'}))
    #tag = forms.CharField(label="标签",required=False,error_messages={'max_length':'标签长度不超过10个字'},max_length=10,widget=forms.TextInput(attrs={'placeholder':'请输入您文章的标签'}))
    #content = forms.MultiValueField

kffz/homepage/views.py
#coding=UTF-8
from django.shortcuts import render, redirect, HttpResponse
import datetime
from django.contrib.auth import authenticate, login as auth_login, logout
from django.views.generic import ListView, DetailView
from homepage.forms import SignupForm
from django.contrib.auth import get_user_model
from . import models
from comment.forms import CommentForm
import markdown
from django.db.models import Q
from django.http import JsonResponse
import json

# Create your views here.


class IndexView(ListView):
    model = models.Blog
    template_name = 'index.html'
    context_object_name = 'blog_list'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        left = []
        right = []
        left_has_more = False
        right_has_more = False
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range
        if page_number == 1:
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last
        }
        return data


class Article_list(IndexView):
    template_name = 'articles-list.html'

class Faq_list(IndexView):
    template_name = 'faq.html'

class Contact_list(IndexView):
    template_name = 'contact.html'

class diy(IndexView):
    template_name = 'diy.html'

class child(IndexView):
    template_name = 'child1.html'

class more(IndexView):
    template_name = 'more1.html'


def signup(request):
    path = request.get_full_path()
    if request.method == 'POST':
        form = SignupForm(data=request.POST, auto_id="%s")
        if form.is_valid():
            UserModel = get_user_model()
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = UserModel.objects.create_user(username=username, email=email, password=password)
            user.save()
            auth_user = authenticate(username=username, password=password)
            auth_login(request, auth_user)
            return redirect('/')
    else:
        form = SignupForm(auto_id='%s')
    return render(request, 'signup.html', locals())


def logout_view(request):
    logout(request)
    return redirect('/')


class BlogDetailView(DetailView):
    model = models.Blog
    template_name = 'single.html'
    context_object_name = 'blog'

    def get(self, request, *args, **kwargs):
        response = super(BlogDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        blog = super(BlogDetailView, self).get_object(queryset=None)
        blog.detail = markdown.markdown(blog.detail,
                                        extensions=[
                                            'markdown.extensions.extra',
                                            'markdown.extensions.codehilite',
                                            'markdown.extensions.toc'
                                        ])
        return blog

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        form = CommentForm
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


def search(request):
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键词'
        return render(request, 'base.html', {'error_msg': error_msg})
    search_blog_list = models.Blog.objects.filter(Q(detail__contains=q) | Q(title__contains=q))
    return render(request, 'base.html', {'error_msg': error_msg, 'search_blog_list': search_blog_list})

kffz/homepage/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block content %}
        <body>
                <!-- Start of Page Container -->
                <div class="page-container">
                        <div class="container">
                                <div class="row">

                                        <!-- start of page content -->
                                        <div class="span8 page-content">

                                                <!-- Basic Home Page Template -->
                                                <div class="row separator">
                                                        <section class="span4 articles-list">
                                                                <h3>Featured Articles</h3>
                                                                {% get_recent_blogs as recent_blog_list %}
                                                                <ul class="articles">
                                                                        {% for blog in recent_blog_list %}
                                                                        <li class="article-entry standard">
                                                                                <h4><a href="single.html">{{ blog.title }}</a></h4>
                                                                                <span class="article-meta">{{ blog.pub_date }}<a href="#" title="View all posts in Server &amp; Database">Server &amp; Database</a></span>
                                                                                <span class="like-count">{{ blog.comment_set.count }}</span>
                                                                        </li>
                                                                        {% empty %}
                                                                        <li class="no-article">
                                                                                <p>暂时没有文章发表</p>
                                                                        </li>
                                                                        {% endfor %}
                                                                </ul>
                                                        </section>


                                                        <section class="span4 articles-list">
                                                                <h3>Latest Articles</h3>
                                                                <ul class="articles">
                                                                        <li class="article-entry standard">
                                                                                <h4><a href="single.html">Integrating WordPress with Your Website</a></h4>
                                                                                <span class="article-meta">25 Feb, 2013 in <a href="#" title="View all posts in Server &amp; Database">Server &amp; Database</a></span>
                                                                                <span class="like-count">66</span>
                                                                        </li>
                                                                        <li class="article-entry standard">
                                                                                <h4><a href="single.html">Using Javascript</a></h4>
                                                                                <span class="article-meta">25 Feb, 2013 in <a href="#" title="View all posts in Advanced Techniques">Advanced Techniques</a></span>
                                                                                <span class="like-count">18</span>
                                                                        </li>
                                                                        <li class="article-entry image">
                                                                                <h4><a href="single.html">Using Images</a></h4>
                                                                                <span class="article-meta">25 Feb, 2013 in <a href="#" title="View all posts in Designing in WordPress">Designing in WordPress</a></span>
                                                                                <span class="like-count">7</span>
                                                                        </li>
                                                                        <li class="article-entry video">
                                                                                <h4><a href="single.html">Using Video</a></h4>
                                                                                <span class="article-meta">24 Feb, 2013 in <a href="#" title="View all posts in WordPress Plugins">WordPress Plugins</a></span>
                                                                                <span class="like-count">7</span>
                                                                        </li>
                                                                        <li class="article-entry standard">
                                                                                <h4><a href="single.html">WordPress Site Maintenance</a></h4>
                                                                                <span class="article-meta">24 Feb, 2013 in <a href="#" title="View all posts in Website Dev">Website Dev</a></span>
                                                                                <span class="like-count">15</span>
                                                                        </li>
                                                                        <li class="article-entry standard">
                                                                                <h4><a href="single.html">WordPress CSS Information and Techniques</a></h4>
                                                                                <span class="article-meta">24 Feb, 2013 in <a href="#" title="View all posts in Theme Development">Theme Development</a></span>
                                                                                <span class="like-count">1</span>
                                                                        </li>
                                                                </ul>
                                                        </section>
                                                </div>
                                        </div>
                                        <!-- end of page content -->

{% endblock %}

kffz/homepage/templates/single.html
{% extends "base.html" %}
{% load static %}
{% block content %}
        <body>
                <!-- Start of Page Container -->
                <div class="page-container">
                        <div class="container">
                                <div class="row">

                                        <!-- start of page content -->
                                        <div class="span8 page-content">

                                                <ul class="breadcrumb">
                                                        <li><a href="#">Knowledge Base Theme</a><span class="divider">/</span></li>
                                                        <li><a href="#" title="View all posts in Server &amp; Database">Server &amp; Database</a> <span class="divider">/</span></li>
                                                        <li class="active">{{blog.title}}</li>
                                                </ul>

                                                <article class=" type-post format-standard hentry clearfix">

                                                        <h1 class="post-title"><a href="#">{{blog.title}}</a></h1>

                                                        <div class="post-meta clearfix">
                                                                <span class="date">{{ blog.pub_date }}</span>
                                                                <span class="author"><a href="#" title="View all posts in Server &amp; Database">{{ blog.authors.username }}</a></span>
                                                                <span class="comments"><a href="#" title="Comment on Integrating WordPress with Your Website">{{ blog.comment_set.count }}</a></span>
                                                                <span class="like-count">{{blog.pingback}}</span>
                                                        </div><!-- end of post meta -->

                                                        <p>{{ blog.detail|safe }}</p>

                                                        <p>{{ blog.detail|safe }}</p>

                                                        <ul>
                                                                <li><strong>You accomplish more</strong>. No, you don’t get more done (you’re doing less, after all), but if you do less and focus on the important stuff, you actually achieve better results, more meaningful accomplishments. This is how I’m able to work less but still write hundreds of posts a year (on various sites), create ebooks and courses, and more.</li>
                                                                <li><strong>You have less anxiety</strong>. When you let go of the distractions and the non-essential, you free yourself from the fear that you need to do these things. You learn that your world doesn’t fall apart when you let these things go.</li>
                                                                <li><strong>You enjoy life more</strong>. Taking time to really focus on an important task, or enjoy the little things, rather than rushing through them, is much more enjoyable.</li>
                                                                <li><strong>You create time</strong>. When you do less, all of a sudden you have free time! What can you do with all that time? How about spend some time with loved ones, read, write, make music, exercise, cook healthy meals, start your own business, meditate, do yoga?</li>
                                                        </ul>

                                                        <h3>Savor Your Tasks</h3>

                                                        <p>I wrote recently about&nbsp;<a href="#">how to savor life</a>&nbsp;… and this applies to your to-do list.</p>

                                                        <ol>
                                                                <li><strong>Take a breath</strong>. Take a moment to pause in your busy day, and breathe. Pay attention to your breath for a minute, then pay attention to your body, how you’re sitting, whether your jaw is clenched, what is tense.</li>
                                                                <li><strong>Now consider your day</strong>. What have you done already today? What is on the horizon for the rest of the day? Is there anything you can let go of? Can you create spaces between your tasks? Can you cull your tasks, getting rid of the non-essential, just leaving the best?</li>
                                                                <li><strong>Learn to know the essential</strong>. It takes time to figure out what tasks give you the most impact on your life, your career, your ability to help others and change the world. But start learning today — pick what you think is most essential, clear some space, and just work on those things. Savor them.</li>
                                                                <li><strong>Reduce distractions</strong>. Consider going on a digital cleanse — take a day or a week off of social media, news, entertainment/gossip sites, the places you usually spend on distractions. What will you do when you feel like some distraction? Meditate, exercise, create.</li>
                                                        </ol>

                                                        <p>Breathe. Enjoy the new space. Savor the beauty of doing less.</p>

                                                </article>

                                                <!--<div class="like-btn">

                                                        <form id="like-it-form" action="#" method="post">
                                                                <span class="like-it ">66</span>
                                                                <input type="hidden" name="post_id" value="99">
                                                                <input type="hidden" name="action" value="like_it">
                                                        </form>

                                                        <span class="tags">
                                                                <strong>Tags:&nbsp;&nbsp;</strong><a href="#" rel="tag">basic</a>, <a href="#" rel="tag">setting</a>, <a href="http://knowledgebase.inspirythemes.com/tag/website/" rel="tag">website</a>
                                                        </span>

                                                </div>-->
                                                <div class="comment-form">
                                                <form action="{% url 'comment:blog_comment' blog.pk %}" method="post" class="comment-form">
                                                        {% csrf_token %}
                                                        <div class="row">
                                                                <div class="col-md-6">
                                                                        <label for="{{ form.name.id_for_label }}">名字：</label>
                                                                        {{form.name}}
                                                                        {{form.name.errors}}
                                                                </div>
                                                                <div class="col-md-6">
                                                                        <label for="{{ form.content.id_for_label }}">评论：</label>
                                                                        {{form.content}}
                                                                        {{form.content.errors}}
                                                                </div>
                                                        </div>
                                                        <div class="form-group margint30">
                                                                <div class="col-sm-offset-2 col-sm-10">
                                                                        <button type="submit" class="btn btn-default">提交</button>
                                                                </div>
                                                        </div>
                                                </form>
                                                <ul class="comment-list list-unstyled">
                                                        {% for comment in comment_list %}
                                                        <li class="comment-item">
                                                                <span class="nickname">{{ comment.name }}</span>
                                                                <time class="sub-time">{{ comment.pub_date }}</time>
                                                                <div class="text">
                                                                        {{ comment.content }}
                                                                </div>
                                                        </li>
                                                        {% empty %}
                                                        暂无评论
                                                        {% endfor %}
                                                </ul>
                                                <!--end of comment-->
                                                </div>
                                                <!-- end of page content -->
                                                </div>
{% endblock %}